
CREATE TABLE FEATURE
( 
  FEATURE_ID VARCHAR2(30) NOT NULL,
  DESCRIPTION VARCHAR2(200),
   CONSTRAINT PK_FEATURE PRIMARY KEY (FEATURE_ID)
);

CREATE TABLE VERSION
( 
  VERSION_ID VARCHAR2(20) NOT NULL,
  DESCRIPTION VARCHAR2(200),
  CONSTRAINT PK_VERSION PRIMARY KEY (VERSION_ID)
);

CREATE TABLE JIRA
( 
  JIRA_ID VARCHAR2(20) NOT NULL,
  DESCRIPTION VARCHAR2(200),
  VERSION VARCHAR2(20) NOT NULL,
  FEATURE VARCHAR2(30) NOT NULL,
  CONSTRAINT PK_JIRA PRIMARY KEY (JIRA_ID),
  CONSTRAINT "JIRA_VERSION" FOREIGN KEY ("VERSION") REFERENCES "VERSION" ("VERSION_ID"),
  CONSTRAINT "JIRA_FEATURE" FOREIGN KEY ("JIRA_ID") REFERENCES "JIRA" ("JIRA_ID")
);


CREATE TABLE PROPERTY_TYPE (
  PROPERTY_TYPE_ID VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(200),
  CONSTRAINT PK_PROPERTY_TYPE PRIMARY KEY (PROPERTY_TYPE_ID)
);

CREATE TABLE PROPERTY
( 
  PROPERTY_KEY VARCHAR2(255) NOT NULL,
  TYPE VARCHAR2(100) NOT NULL, 
  JIRA VARCHAR2(20) NOT NULL,
  CONSTRAINT "PK_PROPERTY" PRIMARY KEY ("PROPERTY_KEY", "TYPE"),
  CONSTRAINT "PROPERTY_PT" FOREIGN KEY ("TYPE") REFERENCES "PROPERTY_TYPE" ("PROPERTY_TYPE_ID"),
  CONSTRAINT "PROPERTY_JIR" FOREIGN KEY ("JIRA") REFERENCES "JIRA" ("JIRA_ID")
);